# Site settings
title: Grid by Example
email: me@rachelandrew.co.uk
description: "My collection of simple examples of the CSS Grid Layout Module."
baseurl: ""
url: "http://gridbyexample.com"
twitter_username: rachelandrew
github_username:  rachelandrew

# Build settings
markdown: kramdown
permalink: pretty

collections:
  resources:
    output: false
  patterns:
    output: true
  examples:
    output: true
  examples2:
    output: true
  video:
    output: true
